name: Save Uploads

on:
  repository_dispatch:
    types: [upload-file]

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Decode and save file
        run: |
          echo "${{ github.event.client_payload.content }}" | base64 -d > "${{ github.event.client_payload.path }}"

      - name: Commit and push
        run: |
          git config --global user.name "Upload Bot"
          git config --global user.email "bot@users.noreply.github.com"
          git add "${{ github.event.client_payload.path }}"
          git commit -m "Add file ${{ github.event.client_payload.path }}"
          git push