name: Upload File Endpoint

on:
  workflow_dispatch:
  repository_dispatch:
    types: [upload-file]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Upload file
        run: |
          echo "$FILE_CONTENT" | base64 --decode > "$FILE_PATH"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add "$FILE_PATH"
          git commit -m "Upload $FILE_NAME"
          git push origin main
        env:
          FILE_NAME: ${{ github.event.client_payload.name }}
          FILE_PATH: ${{ github.event.client_payload.path }}
          FILE_CONTENT: ${{ github.event.client_payload.content }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}