name: Upload File from Web

on:
  repository_dispatch:
    types: [upload-file]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get payload
        id: payload
        run: |
          echo "name=$(jq -r '.client_payload.name' <<< '${{ github.event.client_payload }}')" >> $GITHUB_OUTPUT
          echo "path=$(jq -r '.client_payload.path' <<< '${{ github.event.client_payload }}')" >> $GITHUB_OUTPUT
          echo "content=$(jq -r '.client_payload.content' <<< '${{ github.event.client_payload }}')" >> $GITHUB_OUTPUT

      - name: Save file
        run: |
          mkdir -p "$(dirname ${{ steps.payload.outputs.path }})"
          echo "${{ steps.payload.outputs.content }}" | base64 --decode > "${{ steps.payload.outputs.path }}"

      - name: Commit & Push
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add "${{ steps.payload.outputs.path }}"
          git commit -m "Upload file ${{ steps.payload.outputs.name }} via workflow"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}