name: Upload File

on:
  repository_dispatch:
    types: [upload-file]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get payload
        run: |
          echo "NAME=${{ github.event.client_payload.name }}" >> $GITHUB_ENV
          echo "PATH=${{ github.event.client_payload.path }}" >> $GITHUB_ENV
          echo "CONTENT=${{ github.event.client_payload.content }}" >> $GITHUB_ENV

      - name: Create directories
        run: mkdir -p "$(dirname $PATH)"

      - name: Save file
        run: echo $CONTENT | base64 --decode > $PATH

      - name: Commit & push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add $PATH
          git commit -m "Upload $NAME via workflow"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}